server:
  port: 0

spring:
  application.name: ExploreWithMeMainService
  main.banner-mode: OFF
  jpa:
    show-sql: true
    hibernate.ddl-auto: validate
    properties.hibernate:
      format_sql: true
      jdbc.time_zone: UTC
  sql.init.mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6542/explorewithme
    username: explorewithme
    password: explorewithme

logging.level.org.springframework:
  web.client.RestTemplate: DEBUG
  orm:
    jpa: INFO
    jpa.JpaTransactionManager: DEBUG
  transaction: INFO
  transaction.interceptor: DEBUG

logging.level.ru.practicum.explorewithme: TRACE

service:
  ids:
    stats: ExploreWithMeStatsServer

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${random.value}
    leaseRenewalIntervalInSeconds: 10